"""
Report Generator Agent (Agent 9 of 9) - Deterministic

The final agent in the pipeline. Synthesizes all upstream outputs into
a comprehensive, human-readable ATS analysis report.
"""

import json
from ...shared.python_task_node import PythonTaskNode
from ...shared.utils import get_dict_from_state

def run_report_generator(state: dict) -> str:
    # If the pipeline failed midway, display the error report instead
    if state.get("pipeline_halted"):
        reason = state.get("halt_reason", "Unknown error")
        return f"""---
# 📊 RESUME OPTIMIZER PIPELINE HALTED
**Generated by Resume Optimizer**

❌ The pipeline encountered a fatal error and could not complete processing.

**Reason:**
{reason}

Please check the logs or try again.
---
"""

    jd_out = get_dict_from_state(state.get("jd_analyzer_output", {}))
    align_out = get_dict_from_state(state.get("alignment_validator_output", {}))
    precheck_out = get_dict_from_state(state.get("ats_precheck_output", {}))
    rewriter_out = get_dict_from_state(state.get("resume_rewriter_output", {}))
    scorer_out = get_dict_from_state(state.get("ats_scorer_output", {}))
    critic_out = get_dict_from_state(state.get("critic_output", {}))

    # JD Info
    job_title = jd_out.get("job_title", "Unknown Role")
    seniority = jd_out.get("seniority_level", "Unknown Level")
    emp_type = jd_out.get("employment_type", "Unknown")
    work_model = jd_out.get("work_model", "Unknown")

    # ATS Stats
    score_before = precheck_out.get("ats_score_before", 0)
    score_after = scorer_out.get("ats_score_after", 0)
    score_delta = scorer_out.get("score_delta", "0 points")
    est_pages = critic_out.get("estimated_pages", "N/A")

    # Alignment Check
    cand_label = align_out.get("candidate_label", "Unknown")
    jd_label = align_out.get("jd_label", "Unknown")
    gap = align_out.get("seniority_gap", "N/A")
    domain_overlap = align_out.get("domain_overlap_pct", 0)
    verdict_emoji = "✅ Aligned" if align_out.get("alignment_result") == "pass" else "❌ Rejected"

    # Keywords
    kw_injected = rewriter_out.get("keywords_injected", [])
    injected_str = "\\n".join([f"- {k}" for k in kw_injected]) if kw_injected else "None added"

    kw_missing = scorer_out.get("still_missing_keywords", [])
    missing_str = "\\n".join([f"- {k}" for k in kw_missing]) if kw_missing else "None — all keywords addressed ✅"

    kw_matched = scorer_out.get("matched_keywords_after", [])
    matched_str = "\\n".join([f"- {k}" for k in kw_matched]) if kw_matched else "None"

    # Formatting Warnings
    fmt_check = precheck_out.get("formatting_check", {})
    warnings = fmt_check.get("warnings", [])
    val_warnings_str = ""
    if not warnings:
        val_warnings_str = "No ATS formatting issues detected ✅"
    else:
        for w in warnings:
            val_warnings_str += f"- **[{str(w.get('severity','')).upper()}]** {w.get('message', '')}\\n"

    # Changes Made
    changes = rewriter_out.get("changes_summary", [])
    changes_str = "\\n".join([f"- {c}" for c in changes]) if changes else "No changes documented."

    # Critic Check
    fab = critic_out.get("fabrication_detected", False)
    stuffing = critic_out.get("keyword_stuffing", False)
    jd_quality = critic_out.get("jd_alignment_quality", "Unknown")
    
    crit_verdict = critic_out.get("critic_result", "pass")
    
    # Critical warning section if critic flagged issues
    critical_warning = ""
    if crit_verdict != "pass":
        critical_warning = f"""> [!WARNING]
> Critical Quality Warning
> The Critic Agent flagged the rewritten resume for manual review:
> {critic_out.get('verdict', 'Quality checks failed.')}

"""

    report = f"""---
# 📊 RESUME OPTIMIZATION REPORT
**Generated by Resume Optimizer** | One-Shot Pipeline | MVP01

---

{critical_warning}

## 🎯 Job Target
| Field | Value |
|---|---|
| **Job Title** | {job_title} |
| **Seniority Level** | {seniority} |
| **Employment Type** | {emp_type} |
| **Work Model** | {work_model} |

---

## 📈 ATS Score
| Metric | Value |
|---|---|
| **Score BEFORE rewriting** | {score_before}% |
| **Score AFTER rewriting** | {score_after}% |
| **Improvement** | {score_delta} |
| **Estimated Resume Length** | {est_pages} pages |

---

## ✅ Alignment Check
| Check | Result |
|---|---|
| **Career Level Match** | {cand_label} → {jd_label} (Gap: {gap} level(s)) |
| **Domain Overlap** | {domain_overlap}% |
| **Verdict** | {verdict_emoji} |

---

## 🔑 Keyword Analysis

### Keywords Successfully Injected
{injected_str}

### Keywords Still Missing
{missing_str}
> Note: These keywords couldn't be added without fabricating experience.

### Top JD Keywords Matched After Rewrite
{matched_str}

---

## ⚠️ Formatting Warnings
{val_warnings_str}

---

## 📝 Changes Made
{changes_str}

---

## 🔍 Quality Review (Critic)
| Check | Result |
|---|---|
| **Fabrication Check** | {'✅ Pass' if not fab else '❌ Fail'} |
| **Keyword Stuffing** | {'✅ Clean' if not stuffing else '❌ Detected'} |
| **Page Length** | {est_pages} pages |
| **JD Alignment Quality** | {jd_quality} |

---
*Resume Optimizer — Multi-Agent ATS Optimizer | Built with Google ADK*
"""
    return report

report_generator_agent = PythonTaskNode(
    name="ReportGeneratorAgent",
    task_func=run_report_generator,
    output_key="final_report",
    description="Deterministic node that synthesizes all upstream outputs into an ATS analysis report."
)
