package com.resumeoptimizer.agents;

import com.resumeoptimizer.pipeline.DeterministicAgent;
import com.resumeoptimizer.util.JsonExtractor;

import java.util.List;
import java.util.Map;

/**
 * Agent 9 of 9 — Report Generator (DeterministicAgent).
 * Synthesizes all upstream outputs into a comprehensive ATS analysis report.
 * Direct port of Python's report_generator/agent.py.
 */
public final class ReportGeneratorAgent extends DeterministicAgent {

    private ReportGeneratorAgent() {
        super("ReportGeneratorAgent",
              "Synthesizes all upstream outputs into an ATS analysis report.",
              "final_report");
    }

    public static ReportGeneratorAgent create() { return new ReportGeneratorAgent(); }

    @Override
    @SuppressWarnings("unchecked")
    protected Object execute(Map<String, Object> state) {
        if (Boolean.TRUE.equals(state.get("pipeline_halted"))) {
            String reason = String.valueOf(state.getOrDefault("halt_reason", "Unknown error"));
            return "---\n# 📊 RESUME OPTIMIZER PIPELINE HALTED\n\n❌ " + reason + "\n---\n";
        }

        Map<String, Object> jdOut = JsonExtractor.getDictFromState(state.get("jd_analysis_output"));
        Map<String, Object> alignOut = JsonExtractor.getDictFromState(state.get("alignment_validator_output"));
        Map<String, Object> precheckOut = JsonExtractor.getDictFromState(state.get("ats_precheck_output"));
        Map<String, Object> rewriterOut = JsonExtractor.getDictFromState(state.get("rewriter_output"));
        Map<String, Object> scorerOut = JsonExtractor.getDictFromState(state.get("ats_scorer_output"));
        Map<String, Object> criticOut = JsonExtractor.getDictFromState(state.get("critic_output"));

        String jobTitle = str(jdOut, "job_title", "Unknown Role");
        String seniority = str(jdOut, "seniority_level", "Unknown Level");
        String empType = str(jdOut, "employment_type", "Unknown");
        String workModel = str(jdOut, "work_model", "Unknown");

        Object scoreBefore = precheckOut.getOrDefault("ats_score_before", 0);
        Object scoreAfter = scorerOut.getOrDefault("ats_score_after", 0);
        String scoreDelta = str(scorerOut, "score_delta", "0 points");
        Object estPages = criticOut.getOrDefault("estimated_pages", "N/A");

        String candLabel = str(alignOut, "candidate_label", "Unknown");
        String jdLabel = str(alignOut, "jd_label", "Unknown");
        Object gap = alignOut.getOrDefault("seniority_gap", "N/A");
        Object domainOverlap = alignOut.getOrDefault("domain_overlap_pct", 0);
        String verdictEmoji = "pass".equals(alignOut.get("alignment_result")) ? "✅ Aligned" : "❌ Rejected";

        List<String> kwInjected = (List<String>) rewriterOut.getOrDefault("keywords_injected", List.of());
        String injectedStr = kwInjected.isEmpty() ? "None added" : String.join("\n", kwInjected.stream().map(k -> "- " + k).toList());
        List<String> kwMissing = (List<String>) scorerOut.getOrDefault("still_missing_keywords", List.of());
        String missingStr = kwMissing.isEmpty() ? "None — all keywords addressed ✅" : String.join("\n", kwMissing.stream().map(k -> "- " + k).toList());
        List<String> kwMatched = (List<String>) scorerOut.getOrDefault("matched_keywords_after", List.of());
        String matchedStr = kwMatched.isEmpty() ? "None" : String.join("\n", kwMatched.stream().map(k -> "- " + k).toList());

        Map<String, Object> fmtCheck = JsonExtractor.getDictFromState(precheckOut.get("formatting_check"));
        List<Map<String, Object>> warnings = (List<Map<String, Object>>) fmtCheck.getOrDefault("warnings", List.of());
        String valWarningsStr = warnings.isEmpty() ? "No ATS formatting issues detected ✅"
                : String.join("\n", warnings.stream().map(w -> "- **[" + String.valueOf(w.getOrDefault("severity", "")).toUpperCase() + "]** " + w.getOrDefault("message", "")).toList());

        List<String> changes = (List<String>) rewriterOut.getOrDefault("changes_summary", List.of());
        String changesStr = changes.isEmpty() ? "No changes documented." : String.join("\n", changes.stream().map(c -> "- " + c).toList());

        boolean fab = Boolean.TRUE.equals(criticOut.get("fabrication_detected"));
        boolean stuffing = Boolean.TRUE.equals(criticOut.get("keyword_stuffing"));
        String jdQuality = str(criticOut, "jd_alignment_quality", "Unknown");
        String critVerdict = str(criticOut, "critic_result", "pass");

        String criticalWarning = "";
        if (!"pass".equals(critVerdict)) {
            criticalWarning = "> ⚠️ Critical Quality Warning: " + str(criticOut, "verdict", "Quality checks failed.") + "\n\n";
        }

        return String.format("""
                ---
                # 📊 RESUME OPTIMIZATION REPORT
                **Generated by Resume Optimizer v3** | Java ADK Pipeline
                
                ---
                %s
                ## 🎯 Job Target
                | Field | Value |
                |---|---|
                | **Job Title** | %s |
                | **Seniority Level** | %s |
                | **Employment Type** | %s |
                | **Work Model** | %s |
                
                ---
                ## 📈 ATS Score
                | Metric | Value |
                |---|---|
                | **Score BEFORE** | %s%% |
                | **Score AFTER** | %s%% |
                | **Improvement** | %s |
                | **Estimated Length** | %s pages |
                
                ---
                ## ✅ Alignment Check
                | Check | Result |
                |---|---|
                | **Career Level** | %s → %s (Gap: %s) |
                | **Domain Overlap** | %s%% |
                | **Verdict** | %s |
                
                ---
                ## 🔑 Keywords Injected
                %s
                
                ## 🔑 Keywords Still Missing
                %s
                
                ## 🔑 Keywords Matched After Rewrite
                %s
                
                ---
                ## ⚠️ Formatting Warnings
                %s
                
                ---
                ## 📝 Changes Made
                %s
                
                ---
                ## 🔍 Quality Review (Critic)
                | Check | Result |
                |---|---|
                | **Fabrication** | %s |
                | **Keyword Stuffing** | %s |
                | **Page Length** | %s pages |
                | **JD Alignment** | %s |
                
                ---
                *Resume Optimizer v3 — Multi-Agent ATS Optimizer | Built with Google ADK Java*
                """,
                criticalWarning, jobTitle, seniority, empType, workModel,
                scoreBefore, scoreAfter, scoreDelta, estPages,
                candLabel, jdLabel, gap, domainOverlap, verdictEmoji,
                injectedStr, missingStr, matchedStr, valWarningsStr, changesStr,
                fab ? "❌ Fail" : "✅ Pass", stuffing ? "❌ Detected" : "✅ Clean",
                estPages, jdQuality);
    }

    private static String str(Map<String, Object> map, String key, String defaultVal) {
        Object val = map.get(key);
        return val != null ? String.valueOf(val) : defaultVal;
    }
}
